CREATE TABLE ejercicioclase
	USE ejercicioclase;
    
		CREATE TABLE FABRICANTES
		(
			`COD_FABRICANTE` INT (10) NOT NULL,
            `NOMBRE` VARCHAR (30) NULL,
            `PAIS` VARCHAR (15) NULL
		);
        
        CREATE TABLE ARTICULOS
        (
			`ARTICULO` VARCHAR (20) NOT NULL,
            `COD_FABRICANTE` INT NOT NULL,
            `PESO` INT NOT NULL,
            `CATEGORIA` VARCHAR (10) NOT NULL,
            `PRECIO_VENTA` NUMERIC (6,2) NULL,
            `PRECIO_COSTO` NUMERIC (6,2) NULL,
            `EXISTENCIAS` INT NULL
		);
        
		ALTER TABLE FABRICANTES
		ADD COLUMN PROVINCIA VARCHAR(50),
		ADD PRIMARY KEY (COD_FABRICANTE);
        
        ALTER TABLE ARTICULOS
        ADD PRIMARY KEY (`COD_FABRICANTE`,`PESO`,`ARTICULO`,`CATEGORIA`)
        